version: "3"
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

# 参考：https://docs.gitlab.com/ee/install/docker.html?_gl=1*1xdsyr3*_ga*ODc2NDY3NTUwLjE2NjA1NzA4Nzc.*_ga_ENFH3X7M5Y*MTY2MDU3MDg3Ny4xLjEuMTY2MDU3MDkyMi4w#install-gitlab-using-docker-compose

services:
  gitlab-ce:
    container_name: gitlab-ce
    image: gitlab/gitlab-ce:15.2.2-ce.0
    restart: always
    hostname: git.funnyviki.com
    ports:
      - '80:80'
      - '443:443'
      - '222:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.funnyviki.com'
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - ./data/gitlab-ce/config/:/etc/gitlab/ # 用于存储 GitLab 配置文件
      - ./data/gitlab-ce/logs/:/var/log/gitlab/ # 用于存储日志
      - ./data/gitlab-ce/data/:/var/opt/gitlab/ # 用于存储应用程序数据
    shm_size: 0m
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s 127.0.0.1:80 > /dev/null 2>&1" ]