version: "3"
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s


services:
  gitlab-ce:
    container_name: gitlab-ce
    image: gitlab/gitlab-ce:15.2.2-ce.0
    restart: always
    hostname: 127.0.0.1
    ports:
      - '80:80'
      - '443:443'
      - '222:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.funnyviki.com'
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_username'] = 'postgres'
        gitlab_rails['db_password'] = 'postgres@mima'
        gitlab_rails['db_database'] = "gitlab"
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = 'redis@mima'
        gitlab_rails['redis_database'] = 1
    volumes:
      - ./data/gitlab-ce/config/:/etc/gitlab/ # 用于存储 GitLab 配置文件
      - ./data/gitlab-ce/logs/:/var/log/gitlab/ # 用于存储日志
      - ./data/gitlab-ce/data/:/var/opt/gitlab/ # 用于存储应用程序数据
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s 127.0.0.1:80 > /dev/null 2>&1" ]

  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres@mima
    volumes:
      - ./data/postgresql/data/:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: redis-server --requirepass redis@mima
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data/:/data/
    sysctls:
      net.core.somaxconn: 1024
