version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  rtmp-nginx:
    build:
      context: build
      dockerfile: Dockerfile
    container_name: rtmp-nginx
    image: registry.cn-hangzhou.aliyuncs.com/linxh/rtmp-nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
#    volumes:
      # - /etc/ssl/private/:/etc/ssl/private/ # 配置用于https秘钥,如果有则开启
#      - ./data/nginx/conf.d/:/etc/nginx/conf.d/
#      - ./data/nginx/html/:/usr/share/nginx/html/
#      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s http://127.0.0.1:80 > /dev/null 2>&1" ]

#  ffmpeg:
#    container_name: ffmpeg
#    image: jrottenberg/ffmpeg:latest
#    restart: always
#    command:
#      - -i
#      - "rtsp://admin:123ABCabc@10.10.1.3/"
#      - -vcodec
#      - copy
#      - -acodec
#      - copy
#      - -f
#      - flv
#      - "rtmp://rtmp-nginx:1935/live/"

