version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  nginx-rtsp:
    container_name: nginx-rtsp
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8554:8554"
    volumes:
      - /etc/ssl/private/:/etc/ssl/private/ # 配置用于https秘钥,如果有则开启
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/
      - ./data/nginx/html/:/usr/share/nginx/html/
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s http://127.0.0.1:80 > /dev/null 2>&1" ]
