version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  nginx-rtsp:
    image: nginx:latest
    container_name: nginx-rtsp
    restart: always
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 8080" ]
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8554:8554"
    volumes:
      - /usr/lib64/libssl.so.10:/usr/lib64/libssl.so.10
      - /usr/lib64/libcrypto.so.10:/usr/lib64/libcrypto.so.10
      - /usr/lib64/libpcap.so.1:/usr/lib64/libpcap.so.1
      - /usr/bin/nc:/usr/bin/nc
      - /etc/ssl/private/:/etc/ssl/private/ # 配置用于https秘钥,如果有则开启
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/
      - ./data/nginx/html/:/usr/share/nginx/html/
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
