---
apiVersion: v1
kind: Service
metadata:
  name: milvus
spec:
  ports:
    - name: milvus
      port: 19530
      protocol: TCP
      targetPort: milvus
    - name: milvus-http
      port: 19121
      protocol: TCP
      targetPort: milvus-http
  selector:
    app: milvus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
spec:
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          # 程序客户端使用 1.0.0 ，故无法升级
          image: hub.koalauran.cn:30003/component/milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
          imagePullPolicy: Always
          ports:
            - name: milvus
              containerPort: 19530
              protocol: TCP
            - name: milvus-http
              containerPort: 19121
              protocol: TCP
          volumeMounts:
            - name: milvus-configmap
              mountPath: /var/lib/milvus/conf/server_config.yaml
              subPath: server_config.yaml
            - name: milvus-persistent-storage
              mountPath: /var/lib/milvus/db
              subPath: db
            - name: milvus-persistent-storage
              mountPath: /var/lib/milvus/logs
              subPath: logs
            - name: milvus-persistent-storage
              mountPath: /var/lib/milvus/wal
              subPath: wal
      imagePullSecrets:
        - name: harbor-192.168.2.51-image-pull-secret
      volumes:
        - name: milvus-persistent-storage
          persistentVolumeClaim:
            claimName: milvus-pv-claim
        - name: milvus-configmap
          configMap:
            name: milvus-cm