---
apiVersion: v1
kind: Service
metadata:
  name: go-fastdfs
spec:
  ports:
    - name: go-fastdfs
      nodePort: 38095
      port: 8080
      protocol: TCP
      targetPort: go-fastdfs
  selector:
    app: go-fastdfs
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-fastdfs
spec:
  selector:
    matchLabels:
      app: go-fastdfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-fastdfs
    spec:
      containers:
        - name: go-fastdfs
          image: hub.koalauran.cn:30003/component/sjqzhang/go-fastdfs:v1.4.3
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: GO_FASTDFS_DIR
              value: /data
          ports:
            - name: go-fastdfs
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: go-fastdfs-persistent-storage
              mountPath: /data
              subPath: data
      imagePullSecrets:
        - name: harbor-192.168.2.51-image-pull-secret
      volumes:
        - name: go-fastdfs-persistent-storage
          persistentVolumeClaim:
            claimName: go-fastdfs-pv-claim
