---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: kafka
      nodePort: 49092
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: hub.kaolayouran.cn:5000/osmagic-all/bitnami/kafka:2.5.0
          name: kafka
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: 127.0.0.1:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              # 容器内部无法被外网访问 see: https://www.jianshu.com/p/26495e334613
              value: PLAINTEXT://kafka:9092
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: kafka-persistent-storage
              mountPath: /bitnami/kafka
              subPath: kafka
        - image: hub.kaolayouran.cn:5000/osmagic-all/bitnami/zookeeper:3.5.9
          name: zookeeper
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
              name: zookeeper
          volumeMounts:
            - name: kafka-persistent-storage
              mountPath: /bitnami/zookeeper
              subPath: zookeeper
      volumes:
        - name: kafka-persistent-storage
          persistentVolumeClaim:
            claimName: kafka-pv-claim