---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: mysql
      nodePort: 43306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: hub.kaolayouran.cn:5000/osmagic-all/bitnami/mysql:5.7.36
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: 'GBJ,5jq3V%PUbzQqq@Yr'
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /bitnami/mysql/data
              subPath: data
            - name: mysql-configmap
              mountPath: /opt/bitnami/mysql/conf/bitnami/my_custom.cnf
              subPath: my_custom.cnf
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-configmap
          configMap:
            name: mysql-cm