---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: mysql
      nodePort: 43306
      port: 3306
      protocol: TCP
      targetPort: mysql
  selector:
    app: mysql
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: hub.koalauran.cn:30003/component/bitnami/mysql:8.0.28
          imagePullPolicy: Always
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: 'Koala_MySQL#20Xx..A..'
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /bitnami/mysql/data
              subPath: data
            - name: mysql-configmap
              mountPath: /opt/bitnami/mysql/conf/bitnami/my_custom.cnf
              subPath: my_custom.cnf
      imagePullSecrets:
        - name: harbor-192.168.2.51-image-pull-secret
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-configmap
          configMap:
            name: mysql-cm