---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: redis
      nodePort: 46379
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: hub.kaolayouran.cn:5000/osmagic-all/bitnami/redis:6.2
          name: redis
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - name: redis
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /bitnami/redis
              subPath: redis
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim