---
apiVersion: v1
kind: Service
metadata:
  name: java-03-micro-hyperion
spec:
  ports:
    - name: hyperion
      port: 6300
      protocol: TCP
      targetPort: hyperion
  selector:
    app: java-03-micro-hyperion

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-03-micro-hyperion
spec:
  selector:
    matchLabels:
      app: java-03-micro-hyperion
  template:
    metadata:
      labels:
        app: java-03-micro-hyperion
    spec:
      containers:
        - name: 03-micro-hyperion
          image: hub.kaolayouran.cn:5000/osmagic-all/java-03-micro-hyperion:20220413182054-283
          command: [ "sh", "/home/java/start.sh" ]
          env:
            - name: PARAMETER
              value: --spring.profiles.active=k8s
            - name: JVM_PARAMETER
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Dfile.encoding=UTF-8 -Xmx2G -Xms2G -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_USERNAME
              value: root
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_URL
              value: jdbc:mysql://mysql:3306/osmagic?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_PASSWORD
              value: Koala_MySQL#20Xx..A..
            - name: SPRING_MILVUS_URL
              value: milvus://milvus:19530
          ports:
            - name: hyperion
              containerPort: 6300
              protocol: TCP
      imagePullSecrets:
        - name: harbor-192.168.2.51-image-pull-secret