---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osmagic-cxx-21-dynamic-algo-pv-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi