---
apiVersion: v1
kind: Service
metadata:
  name: web-23-learn-tower
spec:
  ports:
    - name: power
      nodePort: 47302
      port: 7302
      protocol: TCP
      targetPort: tower
  selector:
    app: web-23-learn-tower
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-23-learn-tower
spec:
  selector:
    matchLabels:
      app: web-23-learn-tower
  template:
    metadata:
      labels:
        app: web-23-learn-tower
    spec:
      containers:
        - name: 23-learn-tower
          image: hub.koalauran.cn:30003/osmagic/web-23-learn-tower:20220413182054-283
          ports:
            - name: tower
              containerPort: 7302
              protocol: TCP
          env:
            - name: OSMAGIC_GOFASTDFS
              value: http://go-fastdfs:38095
            - name: DNS_SERVER
              value: 10.96.0.10
          volumeMounts:
            - name: 23-learn-tower-configmap
              mountPath: /etc/nginx/templates/web.conf.template
              subPath: web.conf.template
      imagePullSecrets:
        - name: harbor-192.168.2.51-image-pull-secret
      volumes:
        - name: 23-learn-tower-configmap
          configMap:
            name: osmagic-web-23-tower-cm