---
apiVersion: v1
kind: Service
metadata:
  name: web-21-learn-market
spec:
  ports:
    - name: market
      nodePort: 47102
      port: 7102
      protocol: TCP
      targetPort: market
  selector:
    app: web-21-learn-market
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-21-learn-market
spec:
  selector:
    matchLabels:
      app: web-21-learn-market
  template:
    metadata:
      labels:
        app: web-21-learn-market
    spec:
      containers:
        - name: 21-learn-market
          image: hub.koalauran.cn:30003/osmagic/web-21-learn-market:20220413182054-283
          ports:
            - name: market
              containerPort: 7102
              protocol: TCP
      imagePullSecrets:
        - name: harbor-192.168.2.51-image-pull-secret