---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osmagic-vms-web-pv-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi