---
apiVersion: v1
kind: Service
metadata:
  name: java-02-micro-gateway
spec:
  ports:
    - name: gateway
      nodePort: 46200
      port: 6200
      protocol: TCP
      targetPort: 6200
  selector:
    app: java-02-micro-gateway
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-02-micro-gateway
spec:
  selector:
    matchLabels:
      app: java-02-micro-gateway
  template:
    metadata:
      labels:
        app: java-02-micro-gateway
    spec:
      containers:
        - name: 02-micro-gateway
          image: hub.kaolayouran.cn:5000/osmagic-all/java-02-micro-gateway:20211208190033-39
          command: [ "sh", "/home/java/start.sh" ]
          env:
            - name: PARAMETER
              value: --spring.profiles.active=k8s
            - name: JVM_PARAMETER
              value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Dfile.encoding=UTF-8 -Xmx2G -Xms2G -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
          ports:
            - name: gateway
              containerPort: 6200
              protocol: TCP
