---
apiVersion: v1
kind: Service
metadata:
  name: java-21-learn-bower
spec:
  ports:
    - name: bower
      port: 7100
      protocol: TCP
      targetPort: bower
  selector:
    app: java-21-learn-bower

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-21-learn-bower
spec:
  selector:
    matchLabels:
      app: java-21-learn-bower
  template:
    metadata:
      labels:
        app: java-21-learn-bower
    spec:
      containers:
        - name: 21-learn-bower
          image: hub.koalauran.cn:30003/osmagic/java-21-learn-bower:20220413182054-283
          command: [ "sh", "/home/java/start.sh" ]
          env:
            - name: PARAMETER
              value: --spring.profiles.active=k8s
            - name: JVM_PARAMETER
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Dfile.encoding=UTF-8 -Xmx2G -Xms2G -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_USERNAME
              value: root
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_URL
              value: jdbc:mysql://mysql:3306/osmagic?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_PASSWORD
              value: Koala_MySQL#20Xx..A..
            - name: SPRING_REDIS_URL
              value: redis://redis:6379
          ports:
            - name: tower
              containerPort: 7100
              protocol: TCP
      imagePullSecrets:
        - name: harbor-192.168.2.51-image-pull-secret