---
apiVersion: v1
kind: Service
metadata:
  name: java-22-learn-power
spec:
  ports:
    - name: power
      port: 7100
      protocol: TCP
      targetPort: 7100
  selector:
    app: java-22-learn-power

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-22-learn-power
spec:
  selector:
    matchLabels:
      app: java-22-learn-power
  template:
    metadata:
      labels:
        app: java-22-learn-power
    spec:
      containers:
        - name: 22-learn-power
          image: hub.kaolayouran.cn:5000/osmagic-all/java-22-learn-power:20211208190033-39
          command: [ "sh", "/home/java/start.sh" ]
          env:
            - name: PARAMETER
              value: --spring.profiles.active=k8s
            - name: JVM_PARAMETER
              value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Dfile.encoding=UTF-8 -Xmx2G -Xms2G -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_USERNAME
              value: osmagic
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_URL
              value: "jdbc:mysql://mysql:3306/osmagic?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8"
            - name: SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SQL_PASSWORD
              value: "Koala_MySQL#20Xx..A.."
            - name: SPRING_KAFKA_BOOTSTRAPSERVERS
              value: kafka:9092
            - name: SPRING_REDIS_URL
              value: redis://redis:6379
          ports:
            - name: power
              containerPort: 7100
              protocol: TCP