---
apiVersion: v1
kind: Service
metadata:
  name: web-22-learn-power
spec:
  ports:
    - name: power
      nodePort: 47202
      port: 7202
      protocol: TCP
      targetPort: power
  selector:
    app: web-22-learn-power
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-22-learn-power
spec:
  selector:
    matchLabels:
      app: web-22-learn-power
  template:
    metadata:
      labels:
        app: web-22-learn-power
    spec:
      containers:
        - name: 22-learn-power
          image: hub.koalauran.cn:30003/osmagic/web-22-learn-power:20220413182054-283
          ports:
            - name: power
              containerPort: 7202
              protocol: TCP
          env:
            - name: OSMAGIC_GOFASTDFS
              value: http://go-fastdfs:38095
            - name: DNS_SERVER
              value: 10.96.0.10
          volumeMounts:
            - name: 22-learn-power-configmap
              mountPath: /etc/nginx/templates/web.conf.template
              subPath: web.conf.template
      volumes:
        - name: 22-learn-power-configmap
          configMap:
            name: osmagic-web-22-power-cm
      imagePullSecrets:
        - name: harbor-192.168.2.51-image-pull-secret