apiVersion: v1
kind: ConfigMap
metadata:
  name: osmagic-web-23-tower-cm
data:
  web.conf.template: |
    server {
      listen 7302;
      server_name localhost;
      client_max_body_size 51200m;

      location ~ api {
          proxy_pass  http://java-02-micro-gateway:6200;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection Upgrade;
      }

      location ~ /group1 {
          proxy_pass  ${OSMAGIC_GOFASTDFS};
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection Upgrade;
      }

      location / {
              root /data/web;
              index index.html index.htm;
              try_files $uri $uri/ /index.html;
      }
      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
              root html;
      }
    }