---
apiVersion: v1
kind: Service
metadata:
  name: web-21-learn-market
spec:
  ports:
    - name: market
      nodePort: 47102
      port: 7102
      protocol: TCP
      targetPort: 7102
  selector:
    app: web-21-learn-market
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-21-learn-market
spec:
  selector:
    matchLabels:
      app: web-21-learn-market
  template:
    metadata:
      labels:
        app: web-21-learn-market
    spec:
      containers:
        - name: 21-learn-market
          image: hub.kaolayouran.cn:5000/osmagic-all/web-21-learn-market:20211208190033-39
          ports:
            - name: market
              containerPort: 7102
              protocol: TCP