version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  koala-smart-rongcheng:
    build:
      context: build
      dockerfile: Dockerfile
    container_name: koala-smart-rongcheng
    image: registry.cn-hangzhou.aliyuncs.com/koalauran/koala-smart-rongcheng:1.0.0
    restart: always
    ports:
      - "38080:8080"
    environment:
      MAIN: com.osmagic.smart.SmartRongChengApplication
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD-SHELL","nc -z 127.0.0.1 4010"]
