version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  easyconnect:
    image: hagb/docker-easyconnect:cli
    user: "$UID:$GID"
    container_name: easyconnect
    restart: always
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD-SHELL","nc -z 127.0.0.1 1080"]
    environment:
      EC_VER: 7.6.3
      CLI_OPTS: "-d vpn地址 -u vpn用户名 -p vpn密码"
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "1080:1080"
    volumes:
      - /usr/lib64/libssl.so.10:/usr/lib64/libssl.so.10
      - /usr/lib64/libcrypto.so.10:/usr/lib64/libcrypto.so.10
      - /usr/lib64/libpcap.so.1:/usr/lib64/libpcap.so.1
      - /usr/bin/nc:/usr/bin/nc
      - ./data/easyconnect/:/root/