version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  easyconnect:
    container_name: easyconnect
    image: hagb/docker-easyconnect:cli
    restart: always
    ports:
      - "1080:1080"
    environment:
      EC_VER: 7.6.3
      CLI_OPTS: "-d vpn地址 -u vpn用户名 -p vpn密码"
    volumes:
      - ./data/easyconnect/:/root/
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN