version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  easydarwin:
    build:
      context: build
      dockerfile: Dockerfile
    container_name: easydarwin
    image: registry.cn-hangzhou.aliyuncs.com/linxh/easydarwin:latest
    restart: always
    ports:
      - "554:554"
      - "10008:10008"