---
apiVersion: v1
kind: Service
metadata:
  name: milvus
spec:
  ports:
    - name: milvus
      port: 19530
      protocol: TCP
      targetPort: 19530
    - name: milvus-etcd
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: milvus-minio
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: milvus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
spec:
  selector:
    matchLabels:
      app: milvus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus-etcd
          image: quay.io/coreos/etcd:v3.5.0
          env:
            - name: ETCD_AUTO_COMPACTION_MODE
              value: revision
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1000"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
          command: [ "etcd", "-advertise-client-urls=http://127.0.0.1:2379", "-listen-client-urls", "http://0.0.0.0:2379", "--data-dir", "/etcd" ]
          ports:
            - name: milvus-etcd
              containerPort: 2379
              protocol: TCP
          volumeMounts:
            - name: milvus-persistent-storage
              mountPath: /etcd
              subPath: etcd
        - name: milvus-minio
          image: minio/minio:RELEASE.2020-12-03T00-03-10Z
          env:
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
          command: [ "minio", "server", "/minio_data" ]
          ports:
            - name: milvus-minio
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: milvus-persistent-storage
              mountPath: /minio_data
              subPath: minio
        - name: milvus-standalone
          image: milvusdb/milvus:v2.0.0-rc8-20211104-d1f4106
          env:
            - name: ETCD_ENDPOINTS
              value: milvus:2379
            - name: MINIO_ADDRESS
              value: milvus:9000
          command: [ "milvus", "run", "standalone" ]
          ports:
            - name: milvus
              containerPort: 19530
              protocol: TCP
          volumeMounts:
            - name: milvus-persistent-storage
              mountPath: /var/lib/milvus
              subPath: milvus
      volumes:
        - name: milvus-persistent-storage
          persistentVolumeClaim:
            claimName: milvus-pv-claim