version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  zendao:
    container_name: zendao
    image: idoop/zentao:latest
    restart: always
    ports:
      - "80:80"
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/zendao/:/opt/zbox/
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s http://127.0.0.1:80 > /dev/null 2>&1" ]
