version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql/:/var/lib/mysql/
