version: '3.2'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.34
    restart: always
    # 查看完整可用选项: docker run -it --rm mysql:8.0.34 --verbose --help
    command: --default-time-zone="+8:00" --default-authentication-plugin=mysql_native_password --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max-connections=10240 --log_error_verbosity=3 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: Koala_MySQL#20Xx..A..
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/data/:/var/lib/mysql/