version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  develop-python:
    container_name: develop-python
    entrypoint:
      - /bin/sh
      - -c
      - |
        apt update && \
        apt install -y ssh netcat && \
        sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config && \
        sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/g' /etc/ssh/sshd_config && \
        echo "root:." | chpasswd && \
        /etc/init.d/ssh restart && \
        tail -f dev/null
    image: python:3.7
    restart: always
    ports:
      - "30001:22"
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 22" ]
