mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: '0.0.0.0:9191'
secret: "123456"
external-ui: ui
dns:
  enable: false
  listen: ':53'
  enhanced-mode: fake-ip
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
proxies:
  - { name: '办公', type: socks5, server: 127.0.0.1, port: 2222, udp: true }
  - { name: '🇭🇰 香港 | 9929 [2.5x]', type: trojan, server: updates.sub-zrj.com, port: 321, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: data.sub-zrj.com }
  - { name: '🇭🇰 香港 | CN2 - 2号线', type: trojan, server: ngzyd.sub-zrj.com, port: 321, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇭🇰 香港 | CN2', type: trojan, server: cn2hn.sub-zrj.com, port: 321, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇭🇰 香港 | 上海', type: trojan, server: shlt.sub-zrj.com, port: 321, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇸🇬 新加坡 | 9929 [2.5x]', type: trojan, server: updates.sub-zrj.com, port: 222, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: data.sub-zrj.com }
  - { name: '🇸🇬 新加坡 | CN2', type: trojan, server: cn2hn.sub-zrj.com, port: 222, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇸🇬 新加坡 | CN2 - 2号线', type: trojan, server: ngzyd.sub-zrj.com, port: 222, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇸🇬 新加坡 | 上海', type: trojan, server: shlt.sub-zrj.com, port: 222, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇹🇼 台湾 | 9929 [2.5x]', type: trojan, server: updates.sub-zrj.com, port: 600, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: data.sub-zrj.com }
  - { name: '🇹🇼 台湾 | CN2', type: trojan, server: cn2hn.sub-zrj.com, port: 600, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇹🇼 台湾 | CN2 - 2号线', type: trojan, server: ngzyd.sub-zrj.com, port: 600, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇹🇼 台湾 | 上海', type: trojan, server: shlt.sub-zrj.com, port: 600, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇯🇵 日本 | 9929 [2.5x]', type: trojan, server: updates.sub-zrj.com, port: 2323, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: data.sub-zrj.com }
  - { name: '🇯🇵 日本 | CN2', type: trojan, server: cn2hn.sub-zrj.com, port: 2323, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇯🇵 日本 | CN2 - 2号线', type: trojan, server: ngzyd.sub-zrj.com, port: 2323, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇯🇵 日本 | 上海', type: trojan, server: shlt.sub-zrj.com, port: 2323, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇰🇷 韩国 | 9929 [2.5x]', type: trojan, server: updates.sub-zrj.com, port: 6565, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: data.sub-zrj.com }
  - { name: '🇰🇷 韩国 | CN2', type: trojan, server: cn2hn.sub-zrj.com, port: 6565, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇰🇷 韩国 | CN2 - 2号线', type: trojan, server: ngzyd.sub-zrj.com, port: 6565, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇰🇷 韩国 | 上海', type: trojan, server: shlt.sub-zrj.com, port: 6565, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇺🇸 美国 | 9929 [2.5x]', type: trojan, server: updates.sub-zrj.com, port: 6811, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: data.sub-zrj.com }
  - { name: '🇺🇸 美国 | CN2', type: trojan, server: cn2hn.sub-zrj.com, port: 6811, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇺🇸 美国 | CN2 - 2号线', type: trojan, server: ngzyd.sub-zrj.com, port: 6811, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇺🇸 美国 | 上海', type: trojan, server: shlt.sub-zrj.com, port: 6811, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇬🇧 英国 | 9929 [2.5x]', type: trojan, server: updates.sub-zrj.com, port: 27632, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: data.sub-zrj.com }
  - { name: '🇬🇧 英国 | CN2', type: trojan, server: cn2hn.sub-zrj.com, port: 121, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇬🇧 英国 | CN2 - 2号线', type: trojan, server: ngzyd.sub-zrj.com, port: 121, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
  - { name: '🇬🇧 英国 | 上海', type: trojan, server: shlt.sub-zrj.com, port: 121, password: 53282492-5a67-4acc-917e-01a46a4ade35, udp: true, sni: streaming.sub-zrj.com }
proxy-groups:
  - { name: '🚀 节点选择', type: select, proxies: ['🔯 故障转移', '🔮 负载均衡', '♻️ 自动选择', '🇭🇰 香港 | 9929 [2.5x]', '🇭🇰 香港 | CN2 - 2号线', '🇭🇰 香港 | CN2', '🇭🇰 香港 | 上海', '🇸🇬 新加坡 | 9929 [2.5x]', '🇸🇬 新加坡 | CN2', '🇸🇬 新加坡 | CN2 - 2号线', '🇸🇬 新加坡 | 上海', '🇹🇼 台湾 | 9929 [2.5x]', '🇹🇼 台湾 | CN2', '🇹🇼 台湾 | CN2 - 2号线', '🇹🇼 台湾 | 上海', '🇯🇵 日本 | 9929 [2.5x]', '🇯🇵 日本 | CN2', '🇯🇵 日本 | CN2 - 2号线', '🇯🇵 日本 | 上海', '🇰🇷 韩国 | 9929 [2.5x]', '🇰🇷 韩国 | CN2', '🇰🇷 韩国 | CN2 - 2号线', '🇰🇷 韩国 | 上海', '🇺🇸 美国 | 9929 [2.5x]', '🇺🇸 美国 | CN2', '🇺🇸 美国 | CN2 - 2号线', '🇺🇸 美国 | 上海', '🇬🇧 英国 | 9929 [2.5x]', '🇬🇧 英国 | CN2', '🇬🇧 英国 | CN2 - 2号线', '🇬🇧 英国 | 上海'] }
  - { name: '♻️ 自动选择', type: url-test, proxies: ['🇭🇰 香港 | 9929 [2.5x]', '🇭🇰 香港 | CN2 - 2号线', '🇭🇰 香港 | CN2', '🇭🇰 香港 | 上海', '🇸🇬 新加坡 | 9929 [2.5x]', '🇸🇬 新加坡 | CN2', '🇸🇬 新加坡 | CN2 - 2号线', '🇸🇬 新加坡 | 上海', '🇹🇼 台湾 | 9929 [2.5x]', '🇹🇼 台湾 | CN2', '🇹🇼 台湾 | CN2 - 2号线', '🇹🇼 台湾 | 上海', '🇯🇵 日本 | 9929 [2.5x]', '🇯🇵 日本 | CN2', '🇯🇵 日本 | CN2 - 2号线', '🇯🇵 日本 | 上海', '🇰🇷 韩国 | 9929 [2.5x]', '🇰🇷 韩国 | CN2', '🇰🇷 韩国 | CN2 - 2号线', '🇰🇷 韩国 | 上海', '🇺🇸 美国 | 9929 [2.5x]', '🇺🇸 美国 | CN2', '🇺🇸 美国 | CN2 - 2号线', '🇺🇸 美国 | 上海', '🇬🇧 英国 | 9929 [2.5x]', '🇬🇧 英国 | CN2', '🇬🇧 英国 | CN2 - 2号线', '🇬🇧 英国 | 上海'], url: 'http://www.gstatic.com/generate_204', interval: 86400 }
  - { name: '🔯 故障转移', type: fallback, proxies: ['🇭🇰 香港 | 9929 [2.5x]', '🇭🇰 香港 | CN2 - 2号线', '🇭🇰 香港 | CN2', '🇭🇰 香港 | 上海', '🇸🇬 新加坡 | 9929 [2.5x]', '🇸🇬 新加坡 | CN2', '🇸🇬 新加坡 | CN2 - 2号线', '🇸🇬 新加坡 | 上海', '🇹🇼 台湾 | 9929 [2.5x]', '🇹🇼 台湾 | CN2', '🇹🇼 台湾 | CN2 - 2号线', '🇹🇼 台湾 | 上海', '🇯🇵 日本 | 9929 [2.5x]', '🇯🇵 日本 | CN2', '🇯🇵 日本 | CN2 - 2号线', '🇯🇵 日本 | 上海', '🇰🇷 韩国 | 9929 [2.5x]', '🇰🇷 韩国 | CN2', '🇰🇷 韩国 | CN2 - 2号线', '🇰🇷 韩国 | 上海', '🇺🇸 美国 | 9929 [2.5x]', '🇺🇸 美国 | CN2', '🇺🇸 美国 | CN2 - 2号线', '🇺🇸 美国 | 上海', '🇬🇧 英国 | 9929 [2.5x]', '🇬🇧 英国 | CN2', '🇬🇧 英国 | CN2 - 2号线', '🇬🇧 英国 | 上海'], url: 'http://www.gstatic.com/generate_204', interval: 7200 }
  - { name: '🔮 负载均衡', type: load-balance, proxies: ['🇭🇰 香港 | 9929 [2.5x]', '🇭🇰 香港 | CN2 - 2号线', '🇭🇰 香港 | CN2', '🇭🇰 香港 | 上海', '🇸🇬 新加坡 | 9929 [2.5x]', '🇸🇬 新加坡 | CN2', '🇸🇬 新加坡 | CN2 - 2号线', '🇸🇬 新加坡 | 上海', '🇹🇼 台湾 | 9929 [2.5x]', '🇹🇼 台湾 | CN2', '🇹🇼 台湾 | CN2 - 2号线', '🇹🇼 台湾 | 上海', '🇯🇵 日本 | 9929 [2.5x]', '🇯🇵 日本 | CN2', '🇯🇵 日本 | CN2 - 2号线', '🇯🇵 日本 | 上海', '🇰🇷 韩国 | 9929 [2.5x]', '🇰🇷 韩国 | CN2', '🇰🇷 韩国 | CN2 - 2号线', '🇰🇷 韩国 | 上海', '🇺🇸 美国 | 9929 [2.5x]', '🇺🇸 美国 | CN2', '🇺🇸 美国 | CN2 - 2号线', '🇺🇸 美国 | 上海', '🇬🇧 英国 | 9929 [2.5x]', '🇬🇧 英国 | CN2', '🇬🇧 英国 | CN2 - 2号线', '🇬🇧 英国 | 上海'], url: 'http://www.gstatic.com/generate_204', interval: 300 }
rules:
  - 'DOMAIN-KEYWORD,google,🚀 节点选择' # 域名包含 google
  - 'DOMAIN-KEYWORD,gmail,🚀 节点选择' # 域名包含 gmail
  - 'DOMAIN-SUFFIX,local,DIRECT'
  - 'IP-CIDR,192.168.2.0/24,办公' # 办公网络
  - 'IP-CIDR,10.10.8.0/24,办公' # 办公网络
  - 'IP-CIDR,127.0.0.0/8,DIRECT'
  - 'IP-CIDR,172.16.0.0/12,DIRECT'
  - 'IP-CIDR,192.168.0.0/16,DIRECT'
  - 'IP-CIDR,10.0.0.0/8,DIRECT'
  - 'IP-CIDR,17.0.0.0/8,DIRECT'
  - 'IP-CIDR,100.64.0.0/10,DIRECT'
  - 'IP-CIDR,224.0.0.0/4,DIRECT'
  - 'IP-CIDR6,fe80::/10,DIRECT'
  - 'GEOIP,CN,DIRECT' # 国内直连
  - 'MATCH,🚀 节点选择' # 未成功匹配则, 走代理
