version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  license-client:
    build:
      context: build
      dockerfile: Dockerfile
    container_name: license-client
    image: registry.cn-hangzhou.aliyuncs.com/koalauran/koala-license-client:1.0
    restart: always
    ports:
      - "12000:12000"
    environment:
      LOGGING_LEVEL_COM_KOALA_LICENSE: trace
    volumes:
      - ./data/h2/:/data/H2/
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 12000" ]