---
apiVersion: v1
kind: Service
metadata:
  name: common-zipkin
spec:
  ports:
    - name: zipkin
      port: 9411
      nodePort: 9411
      protocol: TCP
      targetPort: http
  selector:
    app: zipkin
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - name: http
              containerPort: 9411
              protocol: TCP
          env:
            - name: STORAGE_TYPE
              value: mysql
            - name: MYSQL_HOST
              value: common-store-sql-mysql
            - name: MYSQL_TCP_PORT
              value: "3306"
            - name: MYSQL_DB
              value: zipkin
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: Koala_MySQL#20Xx..A..