version: '3'
services:
  frps:
    build:
      context: build/frps
      dockerfile: Dockerfile
    image: registry.cn-chengdu.aliyuncs.com/l-xh/frps:v0.42.0
  frpc:
    build:
      context: build/frpc
      dockerfile: Dockerfile
    image: registry.cn-chengdu.aliyuncs.com/l-xh/frpc:v0.42.0