version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  frp-server:
    container_name: certbot
    image: certbot/certbot:v1.22.0
    restart: always
#    ports:
#      - "7000-7050:7000-7050"
#    environment:
#      FRP_TOKEN: 123
    volumes:
      - ./data/letsencrypt/:/etc/letsencrypt/
      - ./data/lib/letsencrypt/:/var/lib/letsencrypt/
#    healthcheck:
#      <<: *default-healthcheck
#      test: [ "CMD-SHELL","nc -z 127.0.0.1 7000" ]
