version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  frp-server:
    build:
      context: build/frp-server
      dockerfile: Dockerfile
    container_name: frp-server
    image: registry.cn-hangzhou.aliyuncs.com/linxh/frp-server:latest
    restart: always
    ports:
      - "7000-7050:7000-7050"
    environment:
      FRP_TOKEN: 123
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 7000" ]
