version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  redis:
    container_name: redis
    image: redis:7.2.1
    restart: always
    command: redis-server --requirepass ZpQZyRu3c3YcAspqa27V4bx!mKE^acyN
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./data/redis/data/:/data/
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.1'
          memory: 100M
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","redis-cli ping" ]
