version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 6379" ]
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - /usr/lib64/libssl.so.10:/usr/lib64/libssl.so.10
      - /usr/lib64/libcrypto.so.10:/usr/lib64/libcrypto.so.10
      - /usr/lib64/libpcap.so.1:/usr/lib64/libpcap.so.1
      - /usr/bin/nc:/usr/bin/nc
      - ./data/data/:/data/
      - ./data/conf/redis.conf:/etc/redis/redis.conf
