# see https://docs.docker.com/registry/recipes/nginx/
version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  registry:
    container_name: registry
    image: registry:2.7.1
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data/registry/:/var/lib/registry/
    networks:
      - registry-net
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 5000" ]

  registry-nginx:
    container_name: registry-nginx
    image: nginx:1.21.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/certs/:/etc/ssl/private/
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - registry-net
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s --insecure https://127.0.0.1/v2/ > /dev/null 2>&1" ]

networks:
  registry-net: