---
apiVersion: v1
metadata:
  name: pinpoint-cm
data:
  hbase-site.xml: |
    <configuration>
      <property>
        <name>hbase.rootdir</name>
        <value>file:///home/pinpoint/hbase</value>
      </property>
    </configuration>
kind: ConfigMap