apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    SYS_APP: pinpoint-claim
  name: pinpoint-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage