FROM busybox:1.31.0

MAINTAINER lim <xhlim@outlook.com>

ADD https://curl.se/download/curl-7.83.1.tar.gz /home/

RUN mv /home/curl-7.30.0.ermine/curl.ermine /bin/curl \
    && rm -Rf /home/curl-7.30.0.ermine


