version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  aria2-pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    restart: unless-stopped
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
    environment:
      PUID: 65534
      PGID: 65534
      UMASK_SET: 022
      RPC_SECRET: P3TERX
      RPC_PORT: 6800
      LISTEN_PORT: 6888
      DISK_CACHE: 64M
      IPV6_MODE: "false"
      UPDATE_TRACKERS: "true"
      CUSTOM_TRACKER_URL:
      TZ: Asia/Shanghai
    volumes:
      - ./data/aria2/config/:/config/
      - ./data/aria2/downloads/:/downloads/
    logging:
      driver: json-file
      options:
        max-size: 1m
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 6888" ]

  aria-ng:
    container_name: aria-ng
    image: p3terx/ariang
    restart: unless-stopped
    command: --port 6880 --ipv6
    ports:
      - "6880:6880"
    logging:
      driver: json-file
      options:
        max-size: 1m