
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 30081
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: nexus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
    app.kubernetes.io/name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.38.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          volumeMounts:
            - name: nexus-persistent-storage
              mountPath: /nexus-data
      initContainers:
        - args:
            - chown
            - -R
            - "200:200"
            - /data
          image: busybox
          name: busybox
          volumeMounts:
            - name: nexus-persistent-storage
              mountPath: /data
      volumes:
        - name: nexus-persistent-storage
          persistentVolumeClaim:
            claimName: nexus-pv-claim
