version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

x-default-milvus: &default-milvus
  user: "${UID:-1000}:${GID:-1000}"
  image: milvusdb/milvus:1.1.0-cpu-d050721-5e559c
  restart: always
  expose:
    - "19530"
    - "19121"
  healthcheck:
    <<: *default-healthcheck
    test: [ "CMD-SHELL","curl -s http://127.0.0.1:19121 > /dev/null 2>&1" ]

services:
  milvus_cpu:
    <<: *default-milvus
    container_name: milvus_cpu
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - ./data/milvus_cpu/db/:/var/lib/milvus/db/
      - ./data/milvus_cpu/logs/:/var/lib/milvus/logs/
      - ./data/milvus_cpu/wal/:/var/lib/milvus/wal/
      - ./data/milvus_cpu/conf/:/var/lib/milvus/conf/