version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  nginx-h5:
    build:
      context: build
      dockerfile: Dockerfile
    container_name: nginx-h5
    image: registry.cn-hangzhou.aliyuncs.com/linxh/itinerary-code:1.21.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s --insecure http://127.0.0.1:80 > /dev/null 2>&1" ]