version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  clash:
    container_name: clash
    image: dreamacro/clash:v1.10.6
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    volumes:
      - ./ui/.config.yaml:/root/.config/clash/config.yaml
      - ./ui/:/root/.config/clash/ui/
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 7890" ]