version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  fastdfs:
    image: sjqzhang/go-fastdfs
    container_name: go-fastdfs
    restart: always
    healthcheck: 
      <<: *default-healthcheck
      test: ["CMD-SHELL","wget 127.0.0.1:8080 -O /dev/null 2>&1"]
    environment:
      GO_FASTDFS_DIR: /data
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data