version: '3'
services:
  fastdfs:
    image: sjqzhang/go-fastdfs
    container_name: go-fastdfs
    restart: always
    healthcheck: 
      test: ["CMD-SHELL","wget 127.0.0.1:8080 -O /dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    environment:
      GO_FASTDFS_DIR: /data
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data