version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  mongo:
    build:
      context: build/mongo
      dockerfile: Dockerfile
    container_name: mongo
    image: registry.cn-hangzhou.aliyuncs.com/linxh/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: yapi
      MONGO_USERNAME: yapi
      MONGO_PASSWORD: yapi
    volumes:
      - ./data/mongo/db/:/data/db/
      - ./data/mongo/config/:/data/config/

  yapi:
    build:
      context: build/yapi
      dockerfile: Dockerfile
    container_name: yapi
    image: registry.cn-hangzhou.aliyuncs.com/linxh/yapi:latest
    restart: always
    ports:
      - "19090:9090"
      - "13000:3000"
    depends_on:
      - mongo
    volumes:
      - ./data/yapi/:/my-yapi/
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 9090" ]
