version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  yapi:
    build:
      context: build
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/linxh/yapi:latest
    user: "$UID:$GID"
    container_name: yapi
    restart: always
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 9090" ]
    ports:
      - "9090:9090"
    volumes:
      - /usr/lib64/libssl.so.10:/usr/lib64/libssl.so.10
      - /usr/lib64/libcrypto.so.10:/usr/lib64/libcrypto.so.10
      - /usr/lib64/libpcap.so.1:/usr/lib64/libpcap.so.1
      - /usr/bin/nc:/usr/bin/nc