version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:4.4.10
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - ./data/mongo:/bitnami/mongodb

  yapi:
    build:
      context: build/yapi
      dockerfile: Dockerfile
    container_name: yapi
    image: registry.cn-hangzhou.aliyuncs.com/linxh/yapi:latest
    command:
      - /bin/sh
      - -c
      # 如果服务无法访问,请执行: node server/install.js 初始化
      #- sleep 3 && node /yapi/vendors/server/install.js
      - sleep 3 && node /yapi/vendors/server/app.js
    restart: always
    ports:
      - "13000:3000"
    depends_on:
      - mongo
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 3000" ]
