version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  mongo:
    user: "${UID:-1000}:${GID:-1000}"
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongo/db/:/data/db/
      - ./data/mongo/config/:/data/config/

  yapi:
    build:
      context: build
      dockerfile: Dockerfile
    depends_on:
      - mongo
    user: "${UID:-1000}:${GID:-1000}"
    container_name: yapi
    image: registry.cn-hangzhou.aliyuncs.com/linxh/yapi:latest
    restart: always
    ports:
      - "9090:9090"
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 9090" ]
