version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    healthcheck: 
      test: ["CMD-SHELL","curl -s 127.0.0.1:80 > /dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl/private/:/etc/ssl/private/ # 配置用于https秘钥,如果有则开启
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf