---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-192.168.2.51-image-pull-secret
data:
  .dockerconfigjson: {base64 -w 0 "~/.docker/config.json"}
type: kubernetes.io/dockerconfigjson


# cat ~/.docker/config.json
# {
#     "auths": {
#         "hub.koalauran.cn:30003": {
#             "auth": "YWRtaW46SGFyYm9yMTIzNDU="
#         }
#     }
# }