---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pv-claim
  namespace: harbor
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi