version: "3"
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services: 
  web:
    container_name: sonarqube
    image: sonarqube:lts
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./data/sonarqube/conf/:/opt/sonarqube/conf/
      - ./data/sonarqube/data/:/opt/sonarqube/data/
      - ./data/sonarqube/logs/:/opt/sonarqube/logs/
      - ./data/sonarqube/extensions/:/opt/sonarqube/extensions/
      - ./data/sonarqube/lib/bundled-plugins/:/opt/sonarqube/extensions/lib/bundled-plugins/
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 9000" ]