---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
parameters:
  archiveOnDelete: "true" # 删除pvc是否保留数据，"true" 保留
  readOnly: "false"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner