version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/data/:/data/
      - ./data/public/:/public/ # 汉化后的web, 需要自行下载汉化包
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s 127.0.0.1:8080 > /dev/null 2>&1" ]

# 汉化参考: https://www.right.com.cn/forum/thread-4066518-1-1.html
# https://github.com/eysp/public/releases/tag/public