---
kind: Service
apiVersion: v1
metadata:
  name: dind
spec:
  selector:
    name: dind
  ports:
    - protocol: TCP
      port: 2375
      targetPort: 2375

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      containers:
        - name: dind
          image: docker:20.10.18-dind
          args: [ "--insecure-registry=$(REGISTRY)", "--iptables=false" ]
          env:
            - name: REGISTRY
              value: hub.kaolayouran.cn:5000
            - name: DOCKER_TLS_CERTDIR # 默认以 TLS 启动, 监听端口 2376; 设置 DOCKER_TLS_CERTDIR 为空则就以非 TLS 模式启动, 监听端口 2375
              value: ""
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2375
          securityContext:
            # 必须以特权启动
            privileged: true
          tty: true
          volumeMounts:
            - name: dind-temporary-storage
              mountPath: /usr/local/bin/ # docker 可执行程序
              subPath: bin
            - name: dind-temporary-storage
              mountPath: /var/run # docker 通信
              subPath: run
            - name: dind-persistent-storage
              mountPath: /var/lib/docker/ # docker 数据目录
              subPath: docker
          readinessProbe:
            exec:
              command: [ "docker", "info" ]
            initialDelaySeconds: 10
            failureThreshold: 6
          livenessProbe:
            exec:
              command: [ "docker", "info" ]
            initialDelaySeconds: 60
            failureThreshold: 10
      volumes:
        - name: dind-temporary-storage
          emptyDir: { }
        - name: dind-persistent-storage
          persistentVolumeClaim:
            claimName: dind-pv-claim
