version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  koala-hitech-cloud:
    build:
      context: build/koala-hitech-cloud
      dockerfile: Dockerfile
    container_name: koala-hitech-cloud
    image: registry.cn-hangzhou.aliyuncs.com/koalauran/koala-hitech-cloud:0.2.0
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ./data/koala-hitech-cloud/logs/:/usr/local/koala-hitech-cloud/logs/ # 日志目录
      - ./data/koala-hitech-cloud/db/:/root/h2/ # 数据目录
      # - ./data/koala-hitech-cloud/conf/:/usr/local/koala-hitech-cloud/conf/ # 如果需要改动配置，需要将目录中的配置挂载出来
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 8088" ]

  koala-hitech-web-cloud:
    build:
      context: build/koala-hitech-web-cloud
      dockerfile: Dockerfile
    container_name: koala-hitech-web-cloud
    image: registry.cn-hangzhou.aliyuncs.com/koalauran/koala-hitech-web-cloud:0.0.1
    restart: always
    ports:
      - "80:8080"
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s http://127.0.0.1:8080 > /dev/null 2>&1" ]
