version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  jenkins:
    user: "${UID:-1000}:${GID:-1000}"
    container_name: jenkins
    image: jenkins/jenkins:2.246
    restart: always
    entrypoint:
      - /bin/sh
      - -c
      - cp -r -f /usr/share/jenkins/ ${JENKINS_HOME:-/var/jenkins_home/}jenkins/ && tini -- /usr/local/bin/jenkins.sh
    ports:
      - "8080:8080"
    environment:
      JENKINS_WAR: ${JENKINS_HOME:-/var/jenkins_home/}jenkins/jenkins.war
      REF: ${JENKINS_HOME:-/var/jenkins_home/}jenkins/ref
    volumes:
      - ./data/jenkins/:/var/jenkins_home/
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s 127.0.0.1:8080 > /dev/null 2>&1" ]