version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  jenkins:
    image: jenkins/jenkins:2.246
    user: "$UID:$GID"
    container_name: jenkins
    restart: always
    environment: 
      JENKINS_WAR: ${JENKINS_HOME:-/var/jenkins_home/}jenkins/jenkins.war
      REF: ${JENKINS_HOME:-/var/jenkins_home/}jenkins/ref
    entrypoint: 
      - /bin/sh
      - -c
      - cp -r -f /usr/share/jenkins/ ${JENKINS_HOME:-/var/jenkins_home/}jenkins/ && tini -- /usr/local/bin/jenkins.sh
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD-SHELL","nc -z 127.0.0.1 8080"]
    ports:
      - "8080:8080"
    volumes:
      - /usr/lib64/libssl.so.10:/usr/lib64/libssl.so.10
      - /usr/lib64/libcrypto.so.10:/usr/lib64/libcrypto.so.10
      - /usr/lib64/libpcap.so.1:/usr/lib64/libpcap.so.1
      - /usr/bin/nc:/usr/bin/nc
      - ./data/:/var/jenkins_home/