kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yundao-cd-deploy-paas
  labels:
    SYS_APP: yundao-cd-deploy-paas
spec:
  replicas: 1
  selector:
    matchLabels:
      SYS_APP: yundao-cd-deploy-paas
  template:
    metadata:
      labels:
        SYS_APP: yundao-cd-deploy-paas
    spec:
      volumes:
      - name: yundao-cd-deploy-paas-cm-v
        configMap:
          name: yundao-cd-deploy-paas-cm
      containers:
      - name: yundao-cd-deploy-paas
        image: harbor.sh-chinatelecom.yundao.com.cn:8443/yundao-cd-deploy-paas-357/cd-deploy-paas:0.9.1
        ports:
        - containerPort: 8180
          protocol: TCP
        env:
        - name: JAVA_OPTS
          value: "-server -Xmx2688M -Xms2688M -Xmn960M"
        - name: ctgydpaas_app_name
          value: cddeploypaas
        - name: ctgydpaas_app_basepkg
          value: com.yundao.cd.deploy.paas
        - name: ctgydpaas_app_nameserver
          value: http://yundao-cd-eureka.yundao-prod.svc.cluster.local.:8761/eureka
        - name: ctgydpaas_apollo_meta
          value: http://10.128.22.189:31063
        - name: ctgydpaas_apollo_namespaces
          value: application.yml
        - name: ctgydpaas_apollo_appid
          value: yundao-cd-deploy-paas
        - name: ctgydpaas_apollo_cluster
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 128Mi
        imagePullPolicy: Always
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: yundao-cd-deploy-paas
  labels:
    SYS_APP: yundao-cd-deploy-paas
spec:
  ports:
  - name: yundao-cd-deploy-paas
    protocol: TCP
    port: 8180
    targetPort: 8180
    nodePort: 26937
  selector:
    SYS_APP: yundao-cd-deploy-paas
  type: NodePort
