version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  go-fastdfs:
    container_name: go-fastdfs
    image: sjqzhang/go-fastdfs
    restart: always
    ports:
      - "8080:8080"
    environment:
      GO_FASTDFS_DIR: /data
    volumes:
      - ./data/go-fastdfs/:/data/
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 8080" ]