version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  jenkins:
    image: jenkins/jenkins:2.246
    user: "$UID:$GID"
    container_name: jenkins
    restart: always
    environment: 
      JENKINS_WAR: ${JENKINS_HOME:-/var/jenkins_home/}jenkins/jenkins.war
      REF: ${JENKINS_HOME:-/var/jenkins_home/}jenkins/ref
    entrypoint: 
      - /bin/sh
      - -c
      - cp -r -f /usr/share/jenkins/ ${JENKINS_HOME:-/var/jenkins_home/}jenkins/ && tini -- /usr/local/bin/jenkins.sh
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD-SHELL","curl -s http://192.168.2.35:8080 -o /dev/null"]
    ports:
      - "8080:8080"
    volumes:
      - ./data/:/var/jenkins_home/