version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  ql:
    container_name: ql
    image: whyour/qinglong:latest
    hostname: ql
    restart: always
    tty: true
    environment:
      - ENABLE_WEB_PANEL=true
      - ENABLE_HANGUP=true
    volumes:
      - ./data/ql/config/:/ql/config/
      - ./data/ql/log/:/ql/log/
      - ./data/ql/db/:/ql/db/
      - ./data/ql/scripts/:/ql/scripts/
      - ./conf/nginx/conf.d/blocksip.conf:/etc/nginx/conf.d/blocksip.conf
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 5700" ]