version: '3'
x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  ql:
    user: "${UID:-1000}:${GID:-1000}"
    container_name: ql
    image: whyour/qinglong:latest
    hostname: ql
    restart: always
    tty: true
    environment:
      - ENABLE_WEB_PANEL=true
      - ENABLE_HANGUP=true
    volumes:
      - ./data/ql/config/:/ql/config/
      - ./data/ql/log/:/ql/log/
      - ./data/ql/db/:/ql/db/
      - ./data/ql/scripts/:/ql/scripts/
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 5700" ]

  nginx:
    user: "${UID:-1000}:${GID:-1000}"
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "5700:5700"
      - "80:80"
    volumes:
      - /etc/ssl/private/:/etc/ssl/private/ # 配置用于https秘钥,如果有则开启
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/
      - ./data/nginx/html/:/usr/share/nginx/html/
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s http://127.0.0.1:80 > /dev/null 2>&1" ]